services:
    fastapi:
        image: platzi-fastapi
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: platzi-fastapi
        restart: always
        volumes:
            - ../app:/app
            - venv:/opt/venv
        ports:
            - "8000:8000"
        working_dir: /app
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes:
    venv: